cc_library(
    name = "decimal-number",
    deps = ["@com_google_absl//absl/strings"],
    srcs = ["decimal-number.cc"],
    hdrs = ["decimal-number.h", "decimal-number.hpp"],
    visibility = ["//model:__pkg__"],
)

cc_library(
    name = "date",
    hdrs = ["date.h"],
)