load("@rules_cc//cc:defs.bzl", "cc_proto_library")
package(default_visibility = ["//visibility:public"])

proto_library(
    name = "account_proto",
    srcs = ["account.proto"],
    deps = [],
)
cc_proto_library(
    name = "account_cc_proto",
    deps = [":account_proto"],
)

proto_library(
    name = "commodity_proto",
    srcs = ["commodity.proto"],
    deps = [],
)
cc_proto_library(
    name = "commodity_cc_proto",
    deps = [":commodity_proto"],
)

proto_library(
    name = "icon_proto",
    srcs = ["icon.proto"],
    deps = [],
)
cc_proto_library(
    name = "icon_cc_proto",
    deps = [":icon_proto"],
)

proto_library(
    name = "institution_proto",
    srcs = ["institution.proto"],
    deps = [],
)
cc_proto_library(
    name = "institution_cc_proto",
    deps = [":institution_proto"],
)

proto_library(
    name = "payee_proto",
    srcs = ["payee.proto"],
    deps = [],
)
cc_proto_library(
    name = "payee_cc_proto",
    deps = [":payee_proto"],
)

proto_library(
    name = "schedule_proto",
    srcs = ["schedule.proto"],
    deps = [],
)
cc_proto_library(
    name = "schedule_cc_proto",
    deps = [":schedule_proto"],
)

proto_library(
    name = "transaction_proto",
    srcs = ["transaction.proto"],
    deps = [],
)
cc_proto_library(
    name = "transaction_cc_proto",
    deps = [":transaction_proto"],
)