cc_library(
  name = "treap-internal",
  hdrs = ["array-deque.h", "array.h", "binary-search-tree.h", "binary-tree.h", "bst-utils.h", "treap.h", "treap-map.h", "treap-util.h"],
  srcs = ["binary-search-tree.cc"],
  visibility = ["//util:__pkg__"]
  )